### PR TITLE
Whitespace fix

### PR DESCRIPTION
**Pull request by owennw**
I think the whitespace for this file got borked after our messing around creating a release and a new branch.

### CODE REVIEW

**Comment by bjedrzejewski** [comment]
Are we versioning this file in the end? I thought we bring it with grunt

**Comment by owennw** [comment]
maybe you're right and we shouldn't have any of the showcase and its assets versioned. However, they all currently are (and are in release 1 too...).

**Comment by bjedrzejewski** [comment]
So at the moment its just the .js and .css we are building right? Html we are versioning?

**Comment by owennw** [comment]
At the moment it's arguably a bit messed up. We're building the showcase and copying it into our public folder, where it gets renamed and used. Everything from that build is versioned.. *apart* from the styles.css as we've excluded that. Doesn't make a great deal of sense. 

Perhaps we should unversion and remove all the built showcase files. The reason we versioned them originally is because we weren't sure if we were going to be making changes to them before/after building them (including hooks or buttons etc), but we haven't done that yet... YAGNI...

**Comment by bjedrzejewski** [comment]
ok so i am just making another pr to cleanup a bit, as this keeps tripping my git

**Comment by bjedrzejewski** [comment]
Made redundant by #66

**Pull request closed without merging**
