### PR TITLE
Install dev dependencies for d3fc-showcase on npm install

### LINKED ISSUE #86: Build fails ...
After running `npm install` then running the build ...

```
C:\projects\OpenFinD3FC>grunt build
Running "showcase" task
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'time-grunt'
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

Running "copy:main" (copy) task


Running "connect:livereload" (connect) task
Started connect web server on http://0.0.0.0:5000

Done, without errors.
```

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Fixed #86

### CODE REVIEW

**Comment by bjedrzejewski** [comment]
Shall we also clean the travis file in this PR?

**Comment by bjedrzejewski** [comment]
By the way- thank you!

**Comment by bjedrzejewski** [comment]
@ColinEberhardt I made a mistake merging this, as this should be on master. I will remove it with force push.

**Comment by ColinEberhardt** [comment]
@bjedrzejewski I'd have thought it should be merged to 'master' as your current 'public facing' set up is broken. This is more like a release patch than ongoing development work.

**Comment by bjedrzejewski** [comment]
@ColinEberhardt ok, I think we got confused with Nick as we thought that this is locked. Would you mind restarting a PR so we can merge?

**Comment by bjedrzejewski** [comment]
No worries- we managed (Nick managed) to fix it!

**Pull request merged**
